sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
install:
  - pip install flake8
  - pip list
  - flake8 --version
script:
  - nosetests
  - flake8 . --max-line-length=100
notifications:
  email:
    - jtmiller@gmail.com
branches:
  only:
    - master
