sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
install:
  - pip install flake8==2.1.0 pep8==1.5.6
  - python setup.py install
  - pip list
  - flake8 --version
script:
  - nosetests
  - "flake8 --max-line-length=100"
branches:
  only:
    - master
